### ISSUE TITLE
Support path pattern {,*/}

### ISSUE THREAD

**Issue by cburgmer** [thekua/grunt-regex-check#5]
I'd like to match all files, even under subdirectories. Other grunt tasks take something like ```specs/{,*/}*.js```. 

grunt-regex-check will fail with an error:

    Error: Unable to read "test" file (Error code: EISDIR)

**Comment by chesleybrown** [comment]
Wouldn't it just be `specs/**/*.js`?

**Comment by cburgmer** [comment]
As long as I keep the file ending this works. If the pattern ends with a ```"*"``` it breaks. Not sure what the intended behaviour is. I am closing this as the proposed pattern is good enough for me.
